### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by johntdyer** [zertico/jenkins_notifier#1]
Hello,

 Saw this on the [Bitbucket #5095](https://bitbucket.org/site/master/issue/5095/add-branch-information-to-jenkins-service) and I was wondering if you ever got a chance  to do any of those docs u mentioned ? I am not seeing anything but wondering if I maybe missed them somehow?

-John

**Comment by plribeiro3000** [comment]
No. I didnt wrote the documentation yet. Im going to write it in the next week. I will let you know when i do.

Btw, tnx for asking. =D
